### ISSUE TITLE
Centralize input handling

### ISSUE THREAD

**Issue by Froloket64** [SleepySwords/do_todo#44]
So, currently, the input handling _starts_ in `main.rs` in `start_app()`, but then cascades into `stack_layout` and so on. I understand, that it's tempting to implement it in an EDD style, but I don't see any benefit to that. Like, having some `update()` or `draw()` in that way makes sense, it forces all children of a component to be updated or drawn or whatever. But, at least currently, the [implementation](https://github.com/SleepySwords/do_todo/blob/main/src/component/layout/stack_layout.rs#L29-L36) on `StackLayout` literally stops searching for a component that implements a given keybind after one is found, which doesn't require the EDD approach. This can as easily be written as a method on `App` or something, where all keys would be handled. Not only that, but the [`DrawableComponent::key_pressed`](https://github.com/SleepySwords/do_todo/blob/main/src/view.rs#L30-L32) literally inherently requires a `&mut App`, so it would be much less indirection to put it on `App`. + we would eliminate one argument, as `&mut self` would be the app and we would be able to access all components without an argument.

Also, while not bringing any benefits, this only seems to create a lot of confusion for new contributors (like me), who are trying to make sense of **where**'s happening **what**. Because I have lost where which key is handled for the 5th time already and it's quite frustrating and an LSP doesn't help much with that kind of stuff either.

My idea is to, as I said, put everything in one method on `App`, at least for key handling. Although, I think mouse events could also be pretty easily migrated to `App` as well.

**Comment by SleepySwords** [comment]
I assume we would restructure structs so that each component is stored within `App`. This does resolve a lot of code smell since we would just store every component within `App`. 

It might become harder just because `DialogBox` and `InputBox` are currently handled. Unless we handle each type separately, ie:  have a `Vec` for each type of dialogue box within `App` or a single `Vec` with an enum of different types. I didn't really like that just because it feels less flexible, but I guess that should be fine.

Are you intending to make this change, or would you prefer that I did it?

**Comment by Froloket64** [comment]
> Are you intending to make this change, or would you prefer that I did it?

Well, I would like to, but I feel like solving some other ones first. Also, I'm still not sure how to approach that change, so I'll try to think it through for now.

**Comment by SleepySwords** [comment]
Alright, I have a refactor branch, so I'll probably push that to main soon, just so changes don't conflict.

**Comment by Froloket64** [comment]
Oh, yeah, I'm really looking forward to this, because it seems there might be some conflicting changes with what I'm doing locally... Just so we are roughly speaking about the same code)

**Comment by SleepySwords** [comment]
Yea, sorry about that, hopefully, the merge conflicts won't be too bad.
